### ISSUE TITLE
Change the input_shape=(, )

### ISSUE THREAD

**Issue by zdnet** [solivr/tf-crnn#30]
Hi,
i want to change the parameters input_shape in train.py to size (45, 100), but have an exception, could you please help to check?

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [768,1024] rhs shape= [1280,1024]

Thanks

Traceback (most recent call last):
  File "train.py", line 97, in <module>
    image_summaries=True))
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\estimator\estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\estimator\estimator.py", line 815, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1013, in run
    run_metadata=run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [768,1024] rhs shape= [1280,1024]
         [[Node: save/Assign_32 = Assign[T=DT_FLOAT, _class=["loc:@stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/basic_lstm_cell/kernel"], use_locking=true, valida
te_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/basic_lstm_cell/kernel, save/RestoreV2_32)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 108, in <module>
    preprocess_image_for_prediction(min_width=10))
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\estimator\estimator.py", line 550, in export_savedmodel
    saver_for_restore.restore(session, checkpoint_path)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [768,1024] rhs shape= [1280,1024]
         [[Node: save/Assign_32 = Assign[T=DT_FLOAT, _class=["loc:@stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/basic_lstm_cell/kernel"], use_locking=true, valida
te_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/basic_lstm_cell/kernel, save/RestoreV2_32)]]

Caused by op 'save/Assign_32', defined at:
  File "train.py", line 108, in <module>
    preprocess_image_for_prediction(min_width=10))
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\estimator\estimator.py", line 549, in export_savedmodel
    sharded=True)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1239, in __init__
    self.build()
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 759, in _build_internal
    restore_sequentially, reshape)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 471, in _AddShardedRestoreOps
    name="restore_shard"))
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 440, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 62, in assign
    use_locking=use_locking, name=name)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "E:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [768,1024] rhs shape= [1280,1024]
         [[Node: save/Assign_32 = Assign[T=DT_FLOAT, _class=["loc:@stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/basic_lstm_cell/kernel"], use_locking=true, valida
te_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/basic_lstm_cell/kernel, save/RestoreV2_32)]]

**Comment by ivoryxiong** [comment]
you can try to remove model save checkpoint files, maybe cache problem

**Comment by solivr** [comment]
I found the same error when changing the Alphabet during a training. This happens when you restore a model from an existing checkpoint, but the Alphabet has changed in the meantime. As @ivoryxiong suggests, remove the export directory and start new training.
