### ISSUE TITLE
Get prediction results of all images with estimator

### ISSUE THREAD

**Issue by jzhongaa** [solivr/tf-crnn#32]
I managed to use tf.estimator.predict to get the prediction results of a csv file. The size of the images in the csv is not the multiple of batch_size.However, I found that the number of prediction results will always be the multiple of batch_size, which indicates that last batch of images of which the size less than batch size will not be preceeded by tf.estimator.predict and no results will be given for them.

Anyone has solution to it? Thanks in advance!

**Comment by solivr** [comment]
You can set `allow_smaller_final_batch=True` ([this line](https://github.com/solivr/tf-crnn/blob/master/src/data_handler.py#L36)).

**Comment by jzhongaa** [comment]
Hi @solivr : 
Thanks for your reply. I actually tried this before but got another error:

Traceback (most recent call last):
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 468, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 468, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\util\compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 97, in <module>
    image_summaries=True))
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\estimator\estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\lance\Documents\Github\tf-crnn\src\model.py", line 232, in crnn_fn
    conv = deep_cnn(features['images'], (mode == tf.estimator.ModeKeys.TRAIN), summaries=False)
  File "C:\Users\lance\Documents\Github\tf-crnn\src\model.py", line 156, in deep_cnn
    name='reshaped')  # [batch, width, height x features]
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3937, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 229, in _constant_tensor_conversion_
function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\lance\Miniconda3\envs\tf36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 472, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, -1, 512]. Consider casting elements to a supported type.


Could you please help with it? Thanks!

**Comment by solivr** [comment]
I'm not sure on what is going on but it looks like your batch is empty. Did you check that there is no empty line at the end of your file ?

**Comment by jzhongaa** [comment]
@solivr 
With the same dataset(meaning everthing else being same except allow_smaller_final_batch) and setting allow_smaller_final_batch=False, no error will be reported but setting allow_smaller_final_batch=True will result in above error. 

Wonder if there could be other way to solve it. Tks!

**Comment by cipri-tom** [comment]
@jzhongaa are you still seeing this error with the latest version of the code ? I also had it with previous versions due to the batch-part of the `shape` being dynamic when `allow_smaller_final_batch=True`.
I think it should be fixed now.

If not, you can change `shape[0]` with `-1` in [this line]: https://github.com/solivr/tf-crnn/blob/e8a8db1e1f64a64770ed0f5a877d99e26fd9bf55/tf_crnn/model.py#L152 

and also here(`shape[0]*shape[1]` -> `-1`):
https://github.com/solivr/tf-crnn/blob/e8a8db1e1f64a64770ed0f5a877d99e26fd9bf55/tf_crnn/model.py#L185

This allows TensorFlow to compute that dimension of the reshape dynamically
