### ISSUE TITLE
Load Saved Model to predict only one image once cause error 

### ISSUE THREAD

**Issue by ivoryxiong** [solivr/tf-crnn#34]
below is my code 
`
#!/usr/bin/env python

if __name__ == "__main__":
    with tf.Session(graph=tf.Graph()) as sess:
        print("loading model from model dir ...")
        model = PredictionModel("model0/export/1523419345/", sess)
        im = Image.open("oo-1.png").convert('L')
        im = numpy.array(im.getdata(),numpy.uint8).reshape(im.size[0], im.size[1], 1)
        print(im.shape)
        ret = model.predict(im)
        print ("predict result : {}" % (ret))

`
error 
2018-04-11 04:13:01.785282: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Less leaves in the beam search than requested.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/opt/conda/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Less leaves in the beam search than requested.
	 [[Node: code2str_conversion/CTCBeamSearchDecoder = CTCBeamSearchDecoder[beam_width=100, merge_repeated=false, top_paths=2, _device="/job:localhost/replica:0/task:0/cpu:0"](deep_bidirectional_lstm/transpose_time_major, code2str_conversion/Cast_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 24, in <module>
    ret = model.predict(im)
  File "/home/jovyan/work/tf-crnn/src/loader.py", line 22, in predict
    return self.session.run(output, feed_dict={self._input_dict['images']: image})
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Less leaves in the beam search than requested.
	 [[Node: code2str_conversion/CTCBeamSearchDecoder = CTCBeamSearchDecoder[beam_width=100, merge_repeated=false, top_paths=2, _device="/job:localhost/replica:0/task:0/cpu:0"](deep_bidirectional_lstm/transpose_time_major, code2str_conversion/Cast_1)]]

Caused by op 'code2str_conversion/CTCBeamSearchDecoder', defined at:
  File "predict.py", line 18, in <module>
    model = PredictionModel("model0/export/1523419345/", sess)
  File "/home/jovyan/work/tf-crnn/src/loader.py", line 14, in __init__
    self.model = tf.saved_model.loader.load(self.session, ['serve'], model_dir)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 216, in load
    saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1698, in import_meta_graph
    **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 656, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Less leaves in the beam search than requested.
	 [[Node: code2str_conversion/CTCBeamSearchDecoder = CTCBeamSearchDecoder[beam_width=100, merge_repeated=false, top_paths=2, _device="/job:localhost/replica:0/task:0/cpu:0"](deep_bidirectional_lstm/transpose_time_major, code2str_conversion/Cast_1)]]

**Comment by ivoryxiong** [comment]
duplicated to https://github.com/solivr/tf-crnn/issues/4
