### ISSUE TITLE
Error while attempting to train a new model

### ISSUE THREAD

**Issue by HuangHuijuan** [solivr/tf-crnn#35]
I met a problem when I attempted to train a new model. I have no idea where the error comes from. Here is the error message. Thanks!

Traceback (most recent call last):
  File "train.py", line 97, in <module>
    image_summaries=True))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 783, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 537, in __exit__
    self._close_internal(exception_type)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 574, in _close_internal
    self._sess.close()
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 820, in close
    self._sess.close()
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 941, in close
    ignore_live_threads=True)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: paddings must be less than the dimension size: 4, 2 not less than 2
	 [[Node: DataAugmentation/random_padding = MirrorPad[T=DT_UINT8, Tpaddings=DT_INT32, mode="REFLECT", _device="/job:localhost/replica:0/task:0/device:CPU:0"](image_decoding/Merge, DataAugmentation/random_padding/paddings)]]

**Comment by AlanStark** [comment]
Have you managed to solve this problem? I also have this kind of issue.

**Comment by HunterHantao** [comment]
I also have this problem. How do you solve it?

**Comment by jmokoistinen** [comment]
INFO:tensorflow:Using config: {'_model_dir': './model2/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4dfe713400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO - tensorflow - Using config: {'_model_dir': './model2/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4dfe713400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
  0%|                                                                                                                    | 0/10 [00:00<?, ?it/s]INFO:tensorflow:Calling model_fn.
INFO - tensorflow - Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO - tensorflow - Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO - tensorflow - Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO - tensorflow - Graph was finalized.
2018-08-10 16:53:37.448567: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Running local_init_op.
INFO - tensorflow - Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO - tensorflow - Done running local_init_op.

ERROR - CRNN_experiment - Failed after 0:00:09!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: paddings must be less than the dimension size: 6, 0 not less than 3
	 [[Node: DataAugmentation/random_padding = MirrorPad[T=DT_UINT8, Tpaddings=DT_INT32, mode="REFLECT"](cond/Merge, DataAugmentation/random_padding/paddings)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?,32,304,1], [?], [?]], output_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent calls WITHOUT Sacred internals):
  File "train.py", line 119, in run
    image_summaries=True))
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 859, in _train_model_default
    saving_listeners)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1059, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/data/Mika/anaconda3/envs/reOCR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: paddings must be less than the dimension size: 6, 0 not less than 3
	 [[Node: DataAugmentation/random_padding = MirrorPad[T=DT_UINT8, Tpaddings=DT_INT32, mode="REFLECT"](cond/Merge, DataAugmentation/random_padding/paddings)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?,32,304,1], [?], [?]], output_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

training data in format:
folder1/filename1/filename1.png;|t|h|i|s|
folder1/filename2/filename2.png;|i|s|
...

This is not yet solved, here is no reply how to solve.
Do i need to scale all images into same size? [?,32,304,1]...?
What does missing sacred internals mean? I have sacred installed though.
